### ISSUE TITLE
Vertical alignment on top for tables?

### ISSUE THREAD

**Issue by jetkom** [Neftas/supplementary-buttons-anki#105]
Hi!

First of all, thank you very much for your add-on. It has allowed me to make my cards quite a bit more beautiful, which helps me studying. 

As this is a very personal thing though, I've been trying to tweak some things, with no success. My question is: how can I make the tables be aligned vertically on top by default?

I've tried editing the "tables.py" with partial success: I got the tables to align vertically by default, but in turn the width of the columns wouldn't be distributed equally (which is essential for me).

I've tried to disable automatic layout and do my own table styling, but I haven't been able to find a way to have the columns be equally wide.

Thank you very much!

Here is what I modified (added "vertical-align: bottom" to the self.TABLE_STYLING and self.HEAD_STYLING):

```
if self.p.get(const.STYLE_TABLE):
            self.TABLE_STYLING = \
                u"style='font-size: 1em; width: 100%; border-collapse: collapse;vertical-align: bottom;'"
            self.HEAD_STYLING = \
                u"align=\"{0}\" style=\"width: {1}%; padding: 5px;vertical-align: bottom;" \
                + u"border-bottom: 2px solid #00B3FF\""
            self.BODY_STYLING = \
                u"style='text-align: {0}; padding: 5px;vertical-align: bottom;" \
                + u"border-bottom: 1px solid #B0B0B0'"
        else:
            self.TABLE_STYLING = self.HEAD_STYLING = self.BODY_STYLING = u""

        self.setup()
`
```

**Comment by Neftas** [comment]
Hi @jetkom, editing the source code for making changes to styling is very, very fragile, because your changes will be gone every time you update the add-on. And even if you don't, you would be better off using the mechanism that was designed specifically for this type of use cases: CSS style sheets.

I'm sorry to hear that you did not have success creating a style sheet that fits your needs, but I'm afraid my CSS skills are not very good. So although I could go and Google something for you, you will probably be better off asking someone who knows CSS well, play around some more with CSS in a style sheet in a web browser (this would serve you best in the end, because you will be able to solve your own styling problems), or ask a question on a forum like StackOverflow.

Good luck!

**Comment by jetkom** [comment]
Thank you very much for your answer, I'll keep looking.  :-)
