### ISSUE TITLE
Text Highlighting disappeared

### ISSUE THREAD

**Issue by GuitarTab** [Neftas/supplementary-buttons-anki#34]
With the update of 2015-05-23, the text highlighting button has disappeared, the keyboard shortcut doesn't work either. (OSX Yosemite, latest Anki version)

**Comment by Neftas** [comment]
Yes, this is intentional. I'm getting a lot of bug reports from people saying that text highlighting doesn't work for them (in fact, it crashes the addon for them). Text highlighting was and is still available for users on Linux, where it works like a charm.

Why have I deleted this functionality? Unfortunately, Anki strips away the text highlighting tags on Windows and Max OS X, and there isn't a reliable way of adding it for users on those platforms. I wrote a workaround for Windows and Mac OS X a couple of months ago (what you have been using), but I have been getting a steady influx of bug reports concerning text highlighting since then, so I finally decided to delete it completely for Windows and Mac. See https://github.com/Neftas/supplementary-buttons-anki/issues/31 and https://github.com/Neftas/supplementary-buttons-anki/issues/11.

If you do, however, assert that the workaround worked for you on **Mac OS X**, I will consider adding the functionality back for Mac users (and only Windows won't have it).

I recommend of course upgrading to Linux ;-)

**Comment by GuitarTab** [comment]
Thanks very much for replying!

I do, in fact, assert that highlighting worked absolutely perfectly on my Mac.

I'm not a coder or programmer, but I could certainly uncomment some lines of code. So maybe you put the highlighting back in as a comment and tell those of us interested the filename and line numbers ...

Alternatively, I could create a text replacement keyboard shortcut (TextExpander or similar) to quickly insert the font tag in the html editor ...

As to using Linux -- I do, occasionally. I have a second notebook, running Mint  :D

**Comment by Neftas** [comment]
Yes, I tested it on a Mac when I implemented it, of course, and the workaround seemed to work correctly. But the bug reports seemed to imply otherwise, so... Apparently, I need to come up with something different only for Windows, so that's good news :)

Here is what I'll do: I'll re-enable the highlighting for Mac, run a few test to see if everything works like it should when I can get my hands on a Mac (tomorrow), and I'll let you know here when I'm finished and you can upgrade (it will say so on AnkiWeb as well).

Oh by the way, thanks for your rating and comment on AnkiWeb, it's much appreciated :)

**Comment by Neftas** [comment]
Enabled text highlighting for all platforms per faa9e2c672fa8177d2968569df9dab32e5b3a8a9. 

Finally found a way around it, so I hope this solves the issue once and for all.

**Comment by GuitarTab** [comment]
Feedback: Text highlighting works indeed fine again on my Mac, cheers!

For me, text highlighting, clickable hyperlink creation, and lists are the most often use functions, and by a long chalk.

In future, I'll always make a backup before updating Anki add-ons ... ;)

**Comment by Neftas** [comment]
Haha, well, I normally do not delete functionality, only try to enhance it :) 

I'm glad everything works, and please let me know if you find any bugs, or think of any improvements!
