### ISSUE TITLE
Newlines discarded when formatting multiple lines

### ISSUE THREAD

**Issue by sursh** [Neftas/supplementary-buttons-anki#47]
I've noticed that if I write out code that spans multiple lines, like this: 

%load_ex autoreload
%autoreload 2

And then I select those two lines and hit the "Code format text" button, it gets formatted without the newline, like this: 

`%load_ex autoreload %autoreload 2`

**Comment by Neftas** [comment]
You probably want to use the _Create a code block_ button. The _Code format text_ button wraps the text in `<code>` tags. Since block elements cannot exist inside inline elements in HTML, the block disappears. The _Create a code block_ button, on the other hand, wraps the text in `<pre>` tags, thus preserving the whitespace (it is itself a block elements, so no conflict).

I am currently working on a Markdown implementation, so in the future you will be able to wrap your code inside syntax-highlighted blocks by simply indenting the code four spaces or by using back ticks.

**Comment by sursh** [comment]
Ooooh! Very excited to hear about the markdown implementation, as that is
already muscle memory for me. Thanks so much for this great extension!

On Thu, Oct 8, 2015 at 1:50 PM, Stefan van den Akker <
notifications@github.com> wrote:

> You probably want to use the *Create a code block* button. The *Code
> format text* button wraps the text in <code> tags. Since block elements
> cannot exist inside inline elements in HTML, the block disappears. The *Create
> a code block* button, on the other hand, wraps the text in <pre> tags,
> thus preserving the whitespace (it is itself a block elements, so no
> conflict).
>
> I am currently working on a Markdown implementation, so in the future you
> will be able to wrap your code inside syntax-highlighted blocks by simply
> indenting the code four spaces or by using back ticks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Neftas/supplementary-buttons-anki/issues/47#issuecomment-146636560>
> .
>



-- 
-Sasha

**Comment by Neftas** [comment]
Markdown is now implemented, you can download the addon from Ankiweb :)
