### ISSUE TITLE
Applying font changes to tables?

### ISSUE THREAD

**Issue by iyoossaev** [Neftas/supplementary-buttons-anki#49]
Hi,

I was wondering: is there a way to apply any font size to the table? It does ignore the field font size defined in style (so Arial 8 = Arial 14, no difference whatsoever), and all my attempts to put the table within a code block with specified font size failed. The table is just too big for my intenden purpose :(

Thanks in advance,
Mirosław

**Comment by Neftas** [comment]
If the table button doesn't do what you want it to, I can recommend using Markdown to build your table. You will get a "bare-bone" table that you can style to your liking with CSS. Using Markdown will also make sure the table can be changed at any time, because you can easily switch between Markdown and the HTML representation. Let me know if that helps you.
