### ISSUE TITLE
Why is the Power Format Pack shown as Supplementary Buttons for Anki in the app?

### ISSUE THREAD

**Issue by dedu6ka** [Neftas/supplementary-buttons-anki#67]
I have about 20 Add-ons installed;  
it was not easy to figure out that this add-on changes its name :-)  

It would be helpful to   inform us about this metamorphosis right at the TOP of description close.  

Thank you.

**Comment by Neftas** [comment]
Hi @dedu6ka the full name for this addon is "Supplementary Buttons for Anki", because it provides, well, supplementary buttons for AnkiSRS. "Power format pack" was chosen to be included in the description for AnkiWeb because the field there only allows for a certain amount of characters, and "Supplementary Buttons for Anki" was too long. So "power format pack" is more of a description than a name. But I can see why it's confusing. I will include this information more prominently in the description of the addon.

**Comment by dedu6ka** [comment]
Thanks, Stefan.
--------------------------------------------
On Thu, 2/4/16, Stefan van den Akker <notifications@github.com> wrote:

 Subject: Re: [supplementary-buttons-anki] Power format pack.... addon shows up in Anki as "Supplem buttons"  Hm... (#67)
 To: "Neftas/supplementary-buttons-anki" <supplementary-buttons-anki@noreply.github.com>
 Cc: "dedu6ka" <vrem2003-temporary@yahoo.com>
 Date: Thursday, February 4, 2016, 1:53 AM
 
 Hi @dedu6ka the full name
 for this addon is "Supplementary Buttons for
 Anki", because it provides, well, supplementary buttons
 for AnkiSRS. "Power format pack" was chosen to be
 included in the description for AnkiWeb because the field
 there only allows for a certain amount of characters, and
 "Supplementary Buttons for Anki" was too long. So
 "power format pack" is more of a description than
 a name. But I can see why it's confusing. I will include
 this information more prominently in the description of the
 addon.
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by Neftas** [comment]
@dedu6ka I have renamed the add-on inside Anki to "Power Format Pack" in e07768b, which matches the name on AnkiWeb. I hope this will remove any confusion when using this add-on.

You can update the add-on on [AnkiWeb](https://ankiweb.net/shared/info/162313389).
