### ISSUE TITLE
Would you consider making a separate add-on for just ordered/unordered lists? OR...

### ISSUE THREAD

**Issue by jonteamere** [Neftas/supplementary-buttons-anki#76]
OR would you consider modifying your app to allow users to disable features that may be slowing down the editor? It looks like the add-on calls up a whole new (i.e., alternate) card editor. Maybe that's the reason for the slow-down...

Let me know what you think. I think parsing the add-on down to include only essentials like lists would be a great benefit to users.

Thanks!

**Comment by Neftas** [comment]
Hi @jonteamere! I've noticed as well that the editor is sometimes slow to appear, or that switching cards in the card browser is not as fast as one would hope. This has to do with the `onFocus` that is needed for the Markdown part of the addon to work correctly. I have not been able to improve this because I have very little time to work on this addon right now. I have been planning to make the Markdown part optional, so you can disable its functionality completely from the options menu, but I will only be able to do so once my schedule allows, sorry.

**Comment by jonteamere** [comment]
Hey, no problem. I can understand that. I just didn't want this issue to get lost in all the other things you're working on. It's the ONLY reason I had to uninstall the add-on. Thanks for the reply!

**Comment by Neftas** [comment]
@jonteamere I made the Markdown part of this add-on optional in e07768b. It is disabled by default, and so won't slow down card editing anymore. You can update the addon from [AnkiWeb](https://ankiweb.net/shared/info/162313389).
