### ISSUE TITLE
Cannot override code block formatting

### ISSUE THREAD

**Issue by tarzan3** [Neftas/supplementary-buttons-anki#81]
Using markdown, `abc` is converted to `<code>abc</code>` while a code block:
```
 
    ```
    abc
    ```
 
```

is converted to `<div class="codehilite" ...>abc</div>`

If I add a `code { }` section to card CSS, I can control the font-family used for text between `<code>` and `</code>`, among other things. However, if I add a `.codehilite { }` section to card CSS, it doesn't override the font family used for the text between `<div class="codehilite" ...>` and `</div>`. Many other formatting options don't seem to work either. What would I have to change in the addon's code (located in the addons folder) to make this work? Thanks!

**Comment by Neftas** [comment]
When I use Markdown, it gets converted to a div with a class name `codehilite`, and a `pre` child element:

    <div class="codehilite">
        <pre>abc</pre>
    </div>

Since I already style all `pre`s with a certain font family, this font family is also applied to to this Markdown code block.

What you could try is is specify that you want all `pre`'s contained in a `.codehilite` to be given a certain font family:

    .codehilite pre {
        font-familty: monospace;
    }

Depending on your stylesheet, you may want to apply the `!important` rule.

**Comment by tarzan3** [comment]
Sorry for the delay. Both approaches seem to work well. Thanks!
