### ISSUE TITLE
Code formatting addons don't indent text in code?

### ISSUE THREAD

**Issue by pedrohasferreira** [Neftas/supplementary-buttons-anki#88]
I have tried two anki addons with code formatting features. power format pack Syntax Highlighting for Code
With both addons indentation is not preserved. All the text gets indented to the left. For example
this is copied text before code formatting
this is text after formatting with syntax highlight
this is text after formatting from power format pack
In both instances, all the text is indented to the left and original indentation of the code was lost.

**Comment by Neftas** [comment]
Hi @pedrohasferreira it looks like your example code lost its formatting.

Could you maybe post some images, and describe what you would expect when you format your code with this add-on, or what desired behavior would be?

**Comment by pedrohasferreira** [comment]
I would like to make a simple paragraph as it does in Word with the tab keyboard key.

![image](https://cloud.githubusercontent.com/assets/22842220/19397856/01597036-9220-11e6-90f5-6b7a0afdcbc6.png)

Thanks for listening.

**Comment by Neftas** [comment]
@pedrohasferreira I might miss something here, but when I indent my text with spaces, it shows the text with indentation, both in the edit window and when reviewing the card. You can't use tab for that, as you have found out, because that will take the cursor to the next field.

Indenting with spaces won't work if you use Markdown, by the way, because you will create code blocks:

    This is not indented text, this is a code block.

**Comment by pedrohasferreira** [comment]
thanks!!
