### ISSUE TITLE
Question regarding Abbreviations on other platforms

### ISSUE THREAD

**Issue by GitHubScreenName** [Neftas/supplementary-buttons-anki#98]
Please excuse if this is not the correct forum for general questions about the addon - I am new to this and there did not seem to be a listed way to contact you by email or any other addon page without creating an account. First of all, thanks so much for your work on such a great addon. 

A question: will the special formatting that I use on Anki cards using your addon - specifically, the roll-over pop-up abbreviations - be available and show up normally on other Anki platforms? I am using Anki desktop on a Mac. If I export and someone with an Anki program without your addon installed uses this, how will these abbreviations show up? Also, will they show up on the iOs mobile app, in the same manner?

Thanks in advance.

**Comment by Neftas** [comment]
> First of all, thanks so much for your work on such a great addon.

You're welcome :)

> If I export and someone with an Anki program without your addon installed uses this, how will these abbreviations show up?

They will show up the same way as with the add-on. This is because the add-on makes changes to the underlying HTML which are stored as your cards. There is no magic here: you can achieve everything the add-on does by changing the HTML yourself. Go ahead and press <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>X</kbd> when editing a field and you will see the source code. The only thing this add-on do is speed up the process by freeing you from editing the HTML by hand. 

> Also, will they show up on the iOs mobile app, in the same manner?

They should, but since I don't own any Apple hardware, it's hard for me to verify. Also, they abbreviations show up "on hover", when you use the mouse the hover over the abbreviation. I have no idea how this works on a mobile device (maybe you have to tap it?). If you do happen to have an iPhone or other iEquipment, please test this and report back :)
